# Data path. adjust them!
common:
    image_file: "/home/laser/Livox/calibration/data/calib/image/2022-09-20-09-01-21.png"
    pcd_file: "/home/laser/Livox/calibration/data/calib/pcd/2022-09-20-09-01-21.pcd"
    result_file: "/home/laser/Livox/calibration/data/calib/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [4920.29541,    0.0    , 2326.71761,
                       0.0    , 4906.04119, 1535.54928,
                       0.0    ,    0.0    ,    1.0     ]
    dist_coeffs: [-0.502961, 0.257556, -0.008618, -0.010028, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/laser/Livox/calibration/src/livox_camera_calib/config/config_outdoor.yaml"
    #calib_config_file: "/home/laser/Livox/calibration/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
